### ISSUE TITLE
Unable to perform UpdateParameters() function

### ISSUE THREAD

**Issue by BayaneMdW** [mattkjames7/PyGeopack#11]
Hello,
I tried to perform the UpdateParameters() function after installing the package but it doesn't  work.  The issue seems to be that the ftp adress refers to an empty folder : https://github.com/mattkjames7/kpindex/blob/aa5a063301cf55a6648387ff3e615e316d2c8d43/kpindex/Globals.py#L13 .

**Comment by mattkjames7** [comment]
That's odd - it worked for me just a few weeks ago and the ftp site itself shows files on filezilla. Thanks for spotting this - I will look in to it!

**Comment by mattkjames7** [comment]
So, it looks like some  really dodgy coding on my part (nothing unusual there). I have fixed kpindex and uploaded a new package to PyPI. The version with the fixed FTP access is 1.0.1.

Thanks again for spotting this!

https://github.com/mattkjames7/kpindex/releases/tag/v1.0.1
