### ISSUE TITLE
Why only inside Magnetopause?

### ISSUE THREAD

**Issue by ddasilva** [mattkjames7/PyGeopack#12]
I was wondering what is the rational for this code producing NaN's outside the magnetopause. Is there a way to turn that off? The Tsyganenko models are defined outside the magnetopause, and define structure on both sides which would be useful for my analysis.

**Comment by ddasilva** [comment]
Great! Would you mind if we call the option WithinMPOnly? Does defaulting to False work for you?

**Comment by mattkjames7** [comment]
That sounds good to me!
