### ISSUE TITLE
Need to calculate and trace simple dipole field model.

### ISSUE THREAD

**Issue by yw-h** [mattkjames7/PyGeopack#19]
Hello again, what should I do to calculate dipole field without external field model?

**Comment by mattkjames7** [comment]
Good evening,

I have made a slight modification which allows `Model` to be set to `"IGRF"` for both `ModelField()` and `TraceField()`. Technically this is not a dipole field model, but it is just the IGRF internal field model without any external fields. If you update to version 1.2.4 it should work.

I hope that helps!

Cheers.
