### ISSUE TITLE
Silencing "Data file does not exist" Warning

### ISSUE THREAD

**Issue by ddasilva** [mattkjames7/PyGeopack#21]
There are some cases where I just want to use PyGeopack for things like converting between GSM, GEO, SM, etc, and I don't want to download all the data.

The "Data file does not exist" warning is kind of intrusive here, especially when it gets printed 85 times for every subprocess in my program!

I was wondering if there is a way to disable this warning? If not, it might be nice to optionally suppress it with an environmental variable such as `PYGEOPACK_NOWARN=1`

**Comment by mattkjames7** [comment]
I can see that being quite annoying!

I created a new version for this (1.2.5), I called it `GEOPACK_NOWARN` because I also had to check for it in the C++ module that PyGeopack wraps around. Hope that helps!

Cheers!

**Comment by ddasilva** [comment]
Excellent! Thanks!
