### ISSUE TITLE
error_perm: 550 SIZE not allowed in ASCII mode

### ISSUE THREAD

**Issue by fengbopu** [mattkjames7/PyGeopack#23]
The Path have created, but when runing UpdateParameters, the error has appear like title
the error row: 254 raise error_perm(resp)

**Comment by fengbopu** [comment]
Hello, I have add ftp.voidcmd('TYPE I') into source code, problem solved.

**Comment by mattkjames7** [comment]
Hi, 
That's not a bug I have seen before - would you mind telling my what version of PyGeopack, pyomnidata, kpindex and Python you have installed and what operating system you are running so I can see if I can reproduce it please?
Cheers!

**Comment by fengbopu** [comment]
Hi,
Thank you for your reply. PyGeopack: 1.2.5 1.2.6 (both tried), pyomnidata: 1.0.1, kpindex: 2.0.0, Python: 3.10.14 3.12.2 (both tried)
I tried these on win 11 and Ubantu, both appear this error
