### ISSUE TITLE
gp.ModelField() "tilt" argument maybe not work?

### ISSUE THREAD

**Issue by yw-h** [mattkjames7/PyGeopack#25]
When setting tilt=0, results under GSM coord and SM coord should be the same, which is not the case.

`gp.ModelField(x, y, z, int(datetime.strftime(time, "%Y%m%d")), hour+minute/60, "IGRF", "SM", "SM", tilt=0)`
(array([9.34356042]), array([1.07186122]), array([245.97940625]))
`gp.ModelField(x, y, z, int(datetime.strftime(time, "%Y%m%d")), hour+minute/60, "IGRF", "GSM", "GSM", tilt=0)`
(array([63.89468589]), array([2.09112042]), array([243.58096746]))

**Comment by mattkjames7** [comment]
The `tilt` argument was a feature I have been intending to add for a while. It currently doesn't do anything, the best way to find a specific tilt angle is to set the date/time appropriately such that you get the desired tilt at the moment.

**Comment by yw-h** [comment]
thank you!
