### ISSUE TITLE
Explanation of Input parameters for TraceField class

### ISSUE THREAD

**Issue by sterfrag** [mattkjames7/PyGeopack#5]
Hello,

i would like some further explanations (if you may) concerning the inputs of TraceField class. What do you mean by "**x, y and z can either be scalars, or arrays of coordinates in Re**". Also from what i get, the input parameters are GSM by default. Does this mean that i have to provide coordinates in GSM coordinate system? My initial point for example has in geodetic coordinates (lat=80, lon=180 and alt=1500km). Also i do not get what **Re** means. Does it perhaps mean that the input are cartesian coordinates in GSM coordinate system? 

Forgive me if my question is wrong or silly.

**Comment by mattkjames7** [comment]
Hi sterfrag,

Don't worry, your questions are not silly at all! 

So the inputs `x`, `y` and `z` are indeed Cartesian coordinates. Each one can either be a scalar (so you are performing a single trace) or an array (so multiple traces starting from different locations). The units of `x`, `y` and `z` are in R<sub>e</sub> (Earth radii) so 1 R<sub>e</sub> ~ 6371 km. 

The routine accepts three different coordinate systems for input via the `CoordIn` keyword. By default `CoordIn = 'GSM'`, but it could also be set to either `'SM'` or `'GSE'`. The same is true for the output coordinates, which can be specified using the `CoordOut` keyword.

For your example, you would need to convert geodetic coordinates to one of the three Cartesian systems above. I don't think there is a function that does that directly in this module (this could be a feature request that I would be happy to implement), though you could do the following:
1. Use the `GEOtoMAG` function to convert geodetic lat and lon to magnetic lat and lon,
2. Convert MAG lat, lon and altitude to Cartesian MAG coordinates,
3. Use the `MAGtoGSE` function to convert MAG to GSE coordinates,
4. Finally run the trace using the GSE coordinates and by setting `CoordIn='GSE'`.

I hope that helps.
Cheers!

**Comment by sterfrag** [comment]
Thanks a lot for your fast answer Matt. This was extremely helpful.

**Comment by mattkjames7** [comment]
Not a problem!
