### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'I-5min'

### ISSUE THREAD

**Issue by sajlx** [mattkjames7/PyGeopack#6]
PyGeopack/_CalculateParameters.py in _CalculateParameters(SkipWParameters) line 387
how can i help you to resolve this error?

**Comment by mattkjames7** [comment]
Hi sajlx,
Can I ask which version of PyGeopack you have installed, and what steps should I take to reproduce this error?
Thanks!

**Comment by sajlx** [comment]
thanks a lot i make some test and create a lot of folder 
but now it's working
thanks
