### ISSUE TITLE
Unable to run in windows

### ISSUE THREAD

**Issue by Yoshi2112** [mattkjames7/PyGeopack#8]
After setting the appropriate PATH variables to point towards empty folders (as I assumed these would be where data is dumped), I found that I was unable to run this module at all. From your description, you seem to be using Linux - is this module incompatible with windows?

**Comment by mattkjames7** [comment]
Hi Yoshi, I don't think this will work in Windows just yet, it has only really been tested on Linux and Mac.

Does it fail at the point where the module tries to load the shared object file `libgeopack = ct.CDLL(os.path.dirname(__file__)+"/__data/libgeopackdp/libgeopackdp.so")`?

I'm guessing that the main issue would be compiling the Fortran/C code for the model - if you are able to recompile the code stored in `PyGeopack/__data/libgeopackdp` it may work.

I would be happy to attempt to add compatibility with Windows at some point

**Comment by pshustov** [comment]
Hi! There is a recompiled library for Windows [libgeopackdp.zip](https://github.com/mattkjames7/PyGeopack/files/7268497/libgeopackdp.zip). 
But, it's not enough to run PyGeopack in Windows. A few lines of code here, in kpindex, and in pyomnidata contains unix commands. I replaced them by OS-independent Python code, and now it fully works. It's also should work in unix systems. 
I will add all changes to my fork soon. If everything will work well on unix too, you might want to merge it.

**Comment by mattkjames7** [comment]
> Hi! There is a recompiled library for Windows [libgeopackdp.zip](https://github.com/mattkjames7/PyGeopack/files/7268497/libgeopackdp.zip). But, it's not enough to run PyGeopack in Windows. A few lines of code here, in kpindex, and in pyomnidata contain unix commands. I replaced them by OS-independent Python code, and now it fully works. It's also should work in unix systems. I will add all changes to my fork soon. If everything will work well on unix too, you might want to merge it.

Ah great! Thanks for this, I look forward to seeing the changes to the code.

**Comment by mattkjames7** [comment]
Apologies for taking so long with this - I had been in the middle of rewriting much of the backend in C++ and adding features. I have merged all of your Windows-compatible code with the newest C++ code. It all seems to work for me on Windows 10. Thank you very much for the help!

https://github.com/mattkjames7/PyGeopack/releases/tag/v1.0.0
