### ISSUE TITLE
direction in magnetic field tracing

### ISSUE THREAD

**Issue by shihikoo** [mattkjames7/PyGeopack#9]
For field tracing, there is no parameters for request different direction of the tracing: parallel or anti-parallel. Can it be added?

**Comment by mattkjames7** [comment]
Hi Shihikoo,
You are correct - by default it will trace in both directions, I will add an option to do a trace in just one direction.
Cheers!

**Comment by mattkjames7** [comment]
There is now a `TraceDir` keyword which allows tracing in a single direction in this release: https://github.com/mattkjames7/PyGeopack/releases/tag/v1.0.0
